name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        db: [sqlite]
        python-version: [3.8]
    services:
      postgres:
        image: postgres:12.5
        env:
          DEBUG: true
          POSTGRES_DB: dbtest
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
          # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install braintree mysqlclient apprise
    - name: Run Tests
      env:
        DEBUG: true
        POSTGRES_DB: dbtest
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test